/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates the user and automatically opens an initial CHECKING account with a zero balance. The `passwordHash` field carries the plain password; it is hashed server-side.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh JWT tokens
         * @description Exchanges a valid refresh token for a new access token AND a new refresh token (rotation). Clients must replace both stored tokens. Call this when a protected request returns 401.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Authenticates with username and password (sent in the `passwordHash` field) and returns a short-lived access token plus a refresh token.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my accounts, or fetch one by account number
         * @description Without `accountNumber`: a page of the authenticated user's accounts (`page`, `size`, `sort`, e.g. `sort=balance,desc`). With `accountNumber`: the single matching account, which must belong to the user.
         */
        get: operations["getAccounts"];
        put?: never;
        /**
         * Open an additional account
         * @description Creates a new account of the given type for the authenticated user. `initialBalance` defaults to 0.
         */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transfer money to another account
         * @description Moves `amount` from `fromAccountNumber` (must be owned by the caller) to `toAccountNumber` (any existing account, e.g. one of the demo users). Records a DEBIT and a CREDIT FUND_TRANSFER transaction; an optional `note` becomes the description of both.
         */
        post: operations["transfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/pay-bill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pay a bill
         * @description Deducts `amount` from `accountNumber` (must be owned by the caller) and records a BILL_PAYMENT transaction.
         */
        post: operations["payBill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the authenticated user's profile
         * @description Returns the profile (name, email, phone) of the user identified by the bearer token. Useful for greetings and profile screens.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transaction history of one of my accounts
         * @description Paged history for the account with internal ID `accountId` (not the account number). Newest first by default; override with `sort=timestamp,asc`. Each row carries `type`, `direction` (DEBIT = money out, CREDIT = money in), `amount`, UTC `timestamp`, `description` and, for transfers, `relatedAccount`.
         */
        get: operations["getAccountTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one of my accounts by ID */
        get: operations["getAccountById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/transfer/{transactionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one of my transfer transactions by ID */
        get: operations["getTransferDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/pay-bill/{transactionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one of my bill payment transactions by ID */
        get: operations["getBillPaymentDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request DTO for user registration */
        RegisterRequest: {
            /**
             * @description User's unique username
             * @example newuser
             */
            username: string;
            /**
             * @description User's password
             * @example securepassword
             */
            passwordHash: string;
            /**
             * @description User's first name
             * @example Jane
             */
            firstName: string;
            /**
             * @description User's last name
             * @example Doe
             */
            lastName: string;
            /**
             * @description User's unique email address (optional)
             * @example john.doe@example.com
             */
            email?: string;
            /**
             * @description User's phone number
             * @example +1234567890
             */
            phoneNumber: string | null;
        };
        /** @description Standard error payload returned by every failing request */
        ErrorResponse: {
            /**
             * @description UTC time the error was produced (ISO-8601, no offset)
             * @example 2025-06-01T10:30:00.123456
             */
            timestamp: string;
            /**
             * Format: int32
             * @description HTTP status code
             * @example 400
             */
            status: number;
            /**
             * @description HTTP reason phrase
             * @example Bad Request
             */
            error: string;
            /**
             * @description Application error code. AUTH_xxx authentication/user, ACC_xxx account, TXN_xxx transaction, VAL_001 request validation, GEN_001 unexpected error.
             * @example ACC_002
             */
            code: string;
            /**
             * @description Human readable, actionable message
             * @example Insufficient balance in account 1000000001.
             */
            message: string;
            /**
             * @description Request path
             * @example /api/accounts/transfer
             */
            path: string;
        };
        /** @description Response DTO for successful registration */
        RegisterResponse: {
            /**
             * @description Success message
             * @example User newuser registered successfully!
             */
            message: string;
            /**
             * @description Registered username
             * @example newuser
             */
            username: string;
            /**
             * Format: int64
             * @description Unique ID of the registered user
             * @example 3
             */
            userId: number;
            /**
             * @description Initial account number generated for the user
             * @example 1234567890
             */
            initialAccountNumber: string;
        };
        /** @description Request DTO for refreshing access token using refresh token */
        RefreshTokenRequest: {
            /**
             * @description JWT Refresh Token
             * @example eyJhbGciOiJIUzI1Ni...
             */
            refreshToken: string;
        };
        /** @description Response DTO for successful token refresh */
        RefreshTokenResponse: {
            /**
             * @description Success message
             * @example Tokens refreshed successfully!
             */
            message: string;
            /**
             * @description New JWT Access Token
             * @example eyJhbGciOiJIUzI1Ni...
             */
            accessToken: string;
            /**
             * @description New JWT Refresh Token (rotated)
             * @example eyJhbGciOiJIUzI1Ni...
             */
            refreshToken: string;
        };
        /** @description Request DTO for user login */
        LoginRequest: {
            /**
             * @description User's unique username
             * @example user1
             */
            username: string;
            /**
             * @description User's password
             * @example password
             */
            passwordHash: string;
        };
        /** @description Response DTO for successful login */
        LoginResponse: {
            /**
             * @description Success message
             * @example Login successful for user: user1
             */
            message: string;
            /**
             * @description Authenticated username
             * @example user1
             */
            username: string;
            /**
             * Format: int64
             * @description Unique ID of the authenticated user
             * @example 1
             */
            userId: number;
            /**
             * @description JWT Access Token for API calls
             * @example eyJhbGciOiJIUzI1Ni...
             */
            accessToken: string;
            /**
             * @description JWT Refresh Token for renewing access token
             * @example eyJhbGciOiJIUzI1Ni...
             */
            refreshToken: string;
        };
        /** @description Request DTO for creating a new account */
        CreateAccountRequest: {
            /**
             * @description Type of the new account (e.g., CHECKING, SAVINGS)
             * @example SAVINGS
             * @enum {string}
             */
            accountType: "CHECKING" | "SAVINGS" | "MONEY_MARKET" | "INDIVIDUAL_RETIREMENT_ACCOUNT" | "FIXED_TIME_DEPOSIT" | "SPECIAL_BLOCKED_ACCOUNT";
            /**
             * @description Initial balance for the new account
             * @example 50
             */
            initialBalance: number;
        };
        /** @description Response DTO for account details */
        AccountResponse: {
            /**
             * Format: int64
             * @description Unique ID of the account
             * @example 1
             */
            id: number;
            /**
             * @description Account number
             * @example 1234567890
             */
            accountNumber: string;
            /**
             * @description Current balance of the account
             * @example 1000
             */
            balance: number;
            /**
             * Format: int64
             * @description ID of the user who owns this account
             * @example 1
             */
            userId: number;
            /**
             * @description Type of the account (e.g., CHECKING, SAVINGS)
             * @example CHECKING
             * @enum {string}
             */
            accountType: "CHECKING" | "SAVINGS" | "MONEY_MARKET" | "INDIVIDUAL_RETIREMENT_ACCOUNT" | "FIXED_TIME_DEPOSIT" | "SPECIAL_BLOCKED_ACCOUNT";
        };
        /** @description Request DTO for peer-to-peer money transfer */
        TransferRequest: {
            /**
             * @description Account number from which money will be transferred
             * @example 1234567890
             */
            fromAccountNumber: string;
            /**
             * @description Account number to which money will be transferred
             * @example 1122334455
             */
            toAccountNumber: string;
            /**
             * @description Amount to be transferred
             * @example 100.5
             */
            amount: number;
            /**
             * @description Optional note shown as the transaction description on both sides (e.g. 'Rent for September')
             * @example Rent for September
             */
            note?: string | null;
        };
        /** @description Response DTO for a successful transfer */
        TransferResponse: {
            /**
             * @description Success message
             * @example Transfer successful.
             */
            message: string;
            /**
             * @description Amount transferred
             * @example 100.5
             */
            amount: number;
            /**
             * @description Source account number
             * @example 1234567890
             */
            fromAccountNumber: string;
            /**
             * @description Destination account number
             * @example 1122334455
             */
            toAccountNumber: string;
        };
        /** @description Request DTO for bill payment */
        BillPaymentRequest: {
            /**
             * @description Account number from which the bill will be paid
             * @example 0987654321
             */
            accountNumber: string;
            /**
             * @description Name of the biller (e.g., 'Electricity Company')
             * @example Internet Provider
             */
            biller: string;
            /**
             * @description Amount of the bill
             * @example 75
             */
            amount: number;
        };
        /** @description Response DTO for a successful bill payment */
        BillPaymentResponse: {
            /**
             * @description Success message
             * @example Bill payment successful.
             */
            message: string;
            /**
             * @description Amount paid
             * @example 75
             */
            amount: number;
            /**
             * @description Account number from which bill was paid
             * @example 0987654321
             */
            accountNumber: string;
            /**
             * @description Name of the biller
             * @example Internet Provider
             */
            biller: string;
        };
        /** @description Profile of the authenticated user */
        UserResponse: {
            /**
             * Format: int64
             * @description Unique ID of the user
             * @example 1
             */
            id: number;
            /**
             * @description Username
             * @example jane.doe
             */
            username: string;
            /**
             * @description First name
             * @example Jane
             */
            firstName: string;
            /**
             * @description Last name
             * @example Doe
             */
            lastName: string;
            /**
             * @description Email address, may be null
             * @example jane.doe@example.com
             */
            email?: string | null;
            /**
             * @description Phone number
             * @example +251911000000
             */
            phoneNumber: string;
        };
        /** @description A page of results */
        PageResponseTransactionResponse: {
            content: components["schemas"]["TransactionResponse"][];
            /**
             * Format: int64
             * @description Total number of items across all pages
             * @example 24
             */
            totalElements: number;
            /**
             * Format: int32
             * @description Total number of pages
             * @example 3
             */
            totalPages: number;
            /**
             * Format: int32
             * @description Requested page size
             * @example 10
             */
            size: number;
            /**
             * Format: int32
             * @description Zero-based index of this page
             * @example 0
             */
            number: number;
            /**
             * Format: int32
             * @description Number of items on this page
             * @example 10
             */
            numberOfElements: number;
            /** @description True when this is the first page */
            first: boolean;
            /** @description True when this is the last page */
            last: boolean;
            /** @description True when this page has no items */
            empty: boolean;
        };
        /** @description Response DTO for transaction details */
        TransactionResponse: {
            /**
             * Format: int64
             * @description Unique ID of the transaction
             * @example 1
             */
            id: number;
            /**
             * @description Amount of the transaction
             * @example 100
             */
            amount: number;
            /**
             * @description Type of transaction (FUND_TRANSFER, BILL_PAYMENT, TELLER_DEPOSIT)
             * @example FUND_TRANSFER
             * @enum {string}
             */
            type: "FUND_TRANSFER" | "TELLER_TRANSFER" | "ATM_WITHDRAWAL" | "TELLER_DEPOSIT" | "BILL_PAYMENT" | "ACCESS_FEE" | "PURCHASE" | "REFUND" | "INTEREST_EARNED" | "LOAN_PAYMENT";
            /**
             * @description Direction of transaction (DEBIT, CREDIT)
             * @example DEBIT
             * @enum {string}
             */
            direction: "DEBIT" | "CREDIT";
            /**
             * Format: date-time
             * @description Timestamp of the transaction
             */
            timestamp: string;
            /**
             * @description Description of the transaction
             * @example P2P Transfer to 1122334455
             */
            description?: string | null;
            /**
             * @description Related account number for transfers (sender/recipient)
             * @example 1122334455
             */
            relatedAccount?: string | null;
            /**
             * Format: int64
             * @description ID of the account associated with this transaction
             * @example 1
             */
            accountId: number;
            /**
             * @description Account balance right after this transaction. Absent for transactions recorded before this field existed.
             * @example 8390
             */
            balanceAfter?: number | null;
        };
        /** @description A page of accounts */
        PageAccountResponse: {
            content: components["schemas"]["AccountResponse"][];
            /**
             * Format: int64
             * @example 2
             */
            totalElements: number;
            /**
             * Format: int32
             * @example 1
             */
            totalPages: number;
            /**
             * Format: int32
             * @description Requested page size
             * @example 10
             */
            size: number;
            /**
             * Format: int32
             * @description Zero-based page index
             * @example 0
             */
            number: number;
            /**
             * Format: int32
             * @example 2
             */
            numberOfElements: number;
            first: boolean;
            last: boolean;
            empty: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation failed (VAL_001), username taken (AUTH_003) or email taken (AUTH_004) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RefreshTokenResponse"];
                };
            };
            /** @description Validation failed (VAL_001) or a business rule was violated (see `code`) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Refresh token invalid or expired (AUTH_005): the user must log in again */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation failed (VAL_001) or a business rule was violated (see `code`) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid username or password (AUTH_001) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAccounts: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                /** @description Optional: return only the account with this number. */
                accountNumber?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of accounts, or a single account when `accountNumber` is given */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAccountResponse"] | components["schemas"]["AccountResponse"];
                };
            };
            /** @description Missing, invalid or expired access token (AUTH_001 / AUTH_005). Refresh the token and retry. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The account or transaction does not belong to the authenticated user (ACC_004) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found (AUTH_002 user, ACC_001 account, TXN_004 transaction) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (GEN_001) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation failed (VAL_001) or a business rule was violated (see `code`) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing, invalid or expired access token (AUTH_001 / AUTH_005). Refresh the token and retry. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (GEN_001) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    transfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferRequest"];
            };
        };
        responses: {
            /** @description Transfer completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransferResponse"];
                };
            };
            /** @description Validation failed (VAL_001), insufficient funds (ACC_002), same account (ACC_003) or invalid amount (TXN_001) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing, invalid or expired access token (AUTH_001 / AUTH_005). Refresh the token and retry. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The account or transaction does not belong to the authenticated user (ACC_004) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found (AUTH_002 user, ACC_001 account, TXN_004 transaction) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (GEN_001) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    payBill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BillPaymentRequest"];
            };
        };
        responses: {
            /** @description Bill paid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BillPaymentResponse"];
                };
            };
            /** @description Validation failed (VAL_001), insufficient funds (ACC_002) or invalid amount (TXN_001) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing, invalid or expired access token (AUTH_001 / AUTH_005). Refresh the token and retry. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The account or transaction does not belong to the authenticated user (ACC_004) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found (AUTH_002 user, ACC_001 account, TXN_004 transaction) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (GEN_001) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile of the current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Missing, invalid or expired access token (AUTH_001 / AUTH_005). Refresh the token and retry. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (GEN_001) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAccountTransactions: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path: {
                accountId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of transactions (may be empty) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseTransactionResponse"];
                };
            };
            /** @description Missing, invalid or expired access token (AUTH_001 / AUTH_005). Refresh the token and retry. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The account or transaction does not belong to the authenticated user (ACC_004) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found (AUTH_002 user, ACC_001 account, TXN_004 transaction) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (GEN_001) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAccountById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Missing, invalid or expired access token (AUTH_001 / AUTH_005). Refresh the token and retry. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The account or transaction does not belong to the authenticated user (ACC_004) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found (AUTH_002 user, ACC_001 account, TXN_004 transaction) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (GEN_001) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTransferDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transactionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The transfer transaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description The transaction is not a FUND_TRANSFER (TXN_003) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing, invalid or expired access token (AUTH_001 / AUTH_005). Refresh the token and retry. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The account or transaction does not belong to the authenticated user (ACC_004) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found (AUTH_002 user, ACC_001 account, TXN_004 transaction) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (GEN_001) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBillPaymentDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transactionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bill payment transaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description The transaction is not a BILL_PAYMENT (TXN_003) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing, invalid or expired access token (AUTH_001 / AUTH_005). Refresh the token and retry. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The account or transaction does not belong to the authenticated user (ACC_004) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found (AUTH_002 user, ACC_001 account, TXN_004 transaction) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error (GEN_001) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const createAccountRequestAccountTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CreateAccountRequest"]["accountType"]> = ["CHECKING", "SAVINGS", "MONEY_MARKET", "INDIVIDUAL_RETIREMENT_ACCOUNT", "FIXED_TIME_DEPOSIT", "SPECIAL_BLOCKED_ACCOUNT"];
export const accountResponseAccountTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["AccountResponse"]["accountType"]> = ["CHECKING", "SAVINGS", "MONEY_MARKET", "INDIVIDUAL_RETIREMENT_ACCOUNT", "FIXED_TIME_DEPOSIT", "SPECIAL_BLOCKED_ACCOUNT"];
export const transactionResponseTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TransactionResponse"]["type"]> = ["FUND_TRANSFER", "TELLER_TRANSFER", "ATM_WITHDRAWAL", "TELLER_DEPOSIT", "BILL_PAYMENT", "ACCESS_FEE", "PURCHASE", "REFUND", "INTEREST_EARNED", "LOAN_PAYMENT"];
export const transactionResponseDirectionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TransactionResponse"]["direction"]> = ["DEBIT", "CREDIT"];
